[package]
name = "revm-inspectors"
description = "Revm inspector implementations"
version = "0.43.0"
edition = "2021"
rust-version = "1.94"
license = "MIT OR Apache-2.0"
homepage = "https://github.com/paradigmxyz/revm-inspectors"
repository = "https://github.com/paradigmxyz/revm-inspectors"
categories = ["cryptography"]
keywords = ["ethereum", "evm", "inspectors", "tracing", "debugging"]
exclude = [
    ".github",
    "scripts",
    "testdata",
    "tests",
    "cliff.toml",
    "deny.toml",
    "release.toml",
]

[lints]
rust.missing_debug_implementations = "warn"
rust.missing_docs = "warn"
rust.unreachable_pub = "warn"
rust.unused_must_use = "deny"
rust.rust_2018_idioms = "deny"
rustdoc.all = "warn"
clippy.lint_groups_priority = "allow"

[dependencies]
# eth
alloy-rpc-types-eth = { version = "2.0", default-features = false }
alloy-rpc-types-trace = { version = "2.0", default-features = false }
alloy-sol-types = { version = "1.4", default-features = false }
alloy-primitives = { version = "1.4", default-features = false, features = [
    "map",
] }
revm = { version = "43.0.0", default-features = false }

anstyle = { version = "1.0", optional = true }
colorchoice = "1.0"
thiserror = { version = "2.0", default-features = false }

# serde
serde = { version = "1", optional = true, features = ["derive"] }
serde_json = { version = "1.0", default-features = false, features = ["alloc"] }

# js-tracer
boa_engine = { version = "0.21", optional = true }
boa_gc = { version = "0.21", optional = true }

[dev-dependencies]
alloy-hardforks = "0.4"
criterion = "0.8"
snapbox = { version = "1.2", features = ["term-svg"] }

[[bench]]
name = "js_tracer"
path = "benches/js_tracer.rs"
harness = false

[features]
default = ["std"]
std = [
    "alloy-primitives/std",
    "anstyle/std",
    "serde/std",
    "serde_json/std",
    "revm/std",
    "thiserror/std",
]
serde = ["dep:serde", "revm/serde"]
js-tracer = ["dep:boa_engine", "dep:boa_gc"]

[patch.crates-io]
alloy-consensus = { path = "../alloy/crates/consensus" }
alloy-consensus-any = { path = "../alloy/crates/consensus-any" }
alloy-contract = { path = "../alloy/crates/contract" }
alloy-eips = { path = "../alloy/crates/eips" }
alloy-genesis = { path = "../alloy/crates/genesis" }
alloy-json-rpc = { path = "../alloy/crates/json-rpc" }
alloy-network = { path = "../alloy/crates/network" }
alloy-network-primitives = { path = "../alloy/crates/network-primitives" }
alloy-node-bindings = { path = "../alloy/crates/node-bindings" }
alloy-provider = { path = "../alloy/crates/provider" }
alloy-pubsub = { path = "../alloy/crates/pubsub" }
alloy-rpc-client = { path = "../alloy/crates/rpc-client" }
alloy-rpc-types = { path = "../alloy/crates/rpc-types" }
alloy-rpc-types-admin = { path = "../alloy/crates/rpc-types-admin" }
alloy-rpc-types-anvil = { path = "../alloy/crates/rpc-types-anvil" }
alloy-rpc-types-any = { path = "../alloy/crates/rpc-types-any" }
alloy-rpc-types-beacon = { path = "../alloy/crates/rpc-types-beacon" }
alloy-rpc-types-debug = { path = "../alloy/crates/rpc-types-debug" }
alloy-rpc-types-engine = { path = "../alloy/crates/rpc-types-engine" }
alloy-rpc-types-eth = { path = "../alloy/crates/rpc-types-eth" }
alloy-rpc-types-mev = { path = "../alloy/crates/rpc-types-mev" }
alloy-rpc-types-trace = { path = "../alloy/crates/rpc-types-trace" }
alloy-rpc-types-txpool = { path = "../alloy/crates/rpc-types-txpool" }
alloy-serde = { path = "../alloy/crates/serde" }
alloy-signer = { path = "../alloy/crates/signer" }
alloy-signer-local = { path = "../alloy/crates/signer-local" }
alloy-transport = { path = "../alloy/crates/transport" }
alloy-transport-http = { path = "../alloy/crates/transport-http" }
alloy-transport-ipc = { path = "../alloy/crates/transport-ipc" }
alloy-transport-ws = { path = "../alloy/crates/transport-ws" }
alloy-tx-macros = { path = "../alloy/crates/tx-macros" }
alloy-core = { path = "../alloy-core/crates/core" }
alloy-primitives = { path = "../alloy-core/crates/primitives" }
alloy-dyn-abi = { path = "../alloy-core/crates/dyn-abi" }
alloy-json-abi = { path = "../alloy-core/crates/json-abi" }
alloy-sol-types = { path = "../alloy-core/crates/sol-types" }
alloy-sol-macro = { path = "../alloy-core/crates/sol-macro" }
alloy-sol-macro-input = { path = "../alloy-core/crates/sol-macro-input" }
alloy-sol-macro-expander = { path = "../alloy-core/crates/sol-macro-expander" }
alloy-sol-type-parser = { path = "../alloy-core/crates/sol-type-parser" }
syn-solidity = { path = "../alloy-core/crates/syn-solidity" }
alloy-rlp = { path = "../alloy-rlp/crates/rlp" }
alloy-rlp-derive = { path = "../alloy-rlp/crates/rlp-derive" }
alloy-trie = { path = "../alloy-trie" }
alloy-chains = { path = "../alloy-chains" }
alloy-hardforks = { path = "../alloy-hardforks/crates/hardforks" }
alloy-eip2124 = { path = "../alloy-eips/crates/eip2124" }
alloy-eip2930 = { path = "../alloy-eips/crates/eip2930" }
alloy-eip7702 = { path = "../alloy-eips/crates/eip7702" }
alloy-eip7928 = { path = "../alloy-eips/crates/eip7928" }
alloy-eip8141 = { path = "../alloy-eips/crates/eip8141" }
