[workspace]
members = ["crates/*"]
resolver = "2"

[workspace.package]
version = "0.39.0"
edition = "2021"
rust-version = "1.94.1"
authors = ["Alloy Contributors"]
license = "MIT OR Apache-2.0"
homepage = "https://github.com/alloy-rs/alloy-evm"
repository = "https://github.com/alloy-rs/alloy-evm"
exclude = ["benches/", "tests/"]

[workspace.lints.rustdoc]
all = "warn"

[workspace.lints.rust]
missing-debug-implementations = "warn"
missing-docs = "warn"
unreachable-pub = "warn"
unused-must-use = "deny"
rust-2018-idioms = "deny"
unnameable-types = "warn"

[workspace.lints.clippy]
all = { level = "warn", priority = -1 }
missing-const-for-fn = "warn"
use-self = "warn"
option-if-let-else = "allow"
redundant-clone = "warn"

[workspace.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[workspace.dependencies]
alloy-evm = { version = "0.39.0", path = "crates/evm", default-features = false }

# alloy
alloy-eip2124 = { version = "0.2", default-features = false }
alloy-chains = { version = "0.2.0", default-features = false }
alloy-eips = { version = "2.0.0", default-features = false }
alloy-consensus = { version = "2.0.0", default-features = false }
alloy-primitives = { version = "1.0.0", default-features = false }
alloy-sol-types = { version = "1.0.0", default-features = false }
alloy-hardforks = { version = "0.4.7" }
alloy-rpc-types-eth = { version = "2.0.0", default-features = false }
alloy-rpc-types-engine = { version = "2.0.0", default-features = false }

# revm
revm = { version = "43.0.0", default-features = false }

# tracing
tracing = { version = "0.1", default-features = false }

# misc
auto_impl = "1"
derive_more = { version = "2", default-features = false, features = ["full"] }
serde = { version = "1", default-features = false, features = ["derive"] }
thiserror = { version = "2.0.0", default-features = false }
serde_json = "1"
test-case = "3"

[patch.crates-io]
alloy-consensus = { path = "../alloy/crates/consensus" }
alloy-consensus-any = { path = "../alloy/crates/consensus-any" }
alloy-contract = { path = "../alloy/crates/contract" }
alloy-eips = { path = "../alloy/crates/eips" }
alloy-genesis = { path = "../alloy/crates/genesis" }
alloy-json-rpc = { path = "../alloy/crates/json-rpc" }
alloy-network = { path = "../alloy/crates/network" }
alloy-network-primitives = { path = "../alloy/crates/network-primitives" }
alloy-node-bindings = { path = "../alloy/crates/node-bindings" }
alloy-provider = { path = "../alloy/crates/provider" }
alloy-pubsub = { path = "../alloy/crates/pubsub" }
alloy-rpc-client = { path = "../alloy/crates/rpc-client" }
alloy-rpc-types = { path = "../alloy/crates/rpc-types" }
alloy-rpc-types-admin = { path = "../alloy/crates/rpc-types-admin" }
alloy-rpc-types-anvil = { path = "../alloy/crates/rpc-types-anvil" }
alloy-rpc-types-any = { path = "../alloy/crates/rpc-types-any" }
alloy-rpc-types-beacon = { path = "../alloy/crates/rpc-types-beacon" }
alloy-rpc-types-debug = { path = "../alloy/crates/rpc-types-debug" }
alloy-rpc-types-engine = { path = "../alloy/crates/rpc-types-engine" }
alloy-rpc-types-eth = { path = "../alloy/crates/rpc-types-eth" }
alloy-rpc-types-mev = { path = "../alloy/crates/rpc-types-mev" }
alloy-rpc-types-trace = { path = "../alloy/crates/rpc-types-trace" }
alloy-rpc-types-txpool = { path = "../alloy/crates/rpc-types-txpool" }
alloy-serde = { path = "../alloy/crates/serde" }
alloy-signer = { path = "../alloy/crates/signer" }
alloy-signer-local = { path = "../alloy/crates/signer-local" }
alloy-transport = { path = "../alloy/crates/transport" }
alloy-transport-http = { path = "../alloy/crates/transport-http" }
alloy-transport-ipc = { path = "../alloy/crates/transport-ipc" }
alloy-transport-ws = { path = "../alloy/crates/transport-ws" }
alloy-tx-macros = { path = "../alloy/crates/tx-macros" }
alloy-core = { path = "../alloy-core/crates/core" }
alloy-primitives = { path = "../alloy-core/crates/primitives" }
alloy-dyn-abi = { path = "../alloy-core/crates/dyn-abi" }
alloy-json-abi = { path = "../alloy-core/crates/json-abi" }
alloy-sol-types = { path = "../alloy-core/crates/sol-types" }
alloy-sol-macro = { path = "../alloy-core/crates/sol-macro" }
alloy-sol-macro-input = { path = "../alloy-core/crates/sol-macro-input" }
alloy-sol-macro-expander = { path = "../alloy-core/crates/sol-macro-expander" }
alloy-sol-type-parser = { path = "../alloy-core/crates/sol-type-parser" }
syn-solidity = { path = "../alloy-core/crates/syn-solidity" }
alloy-rlp = { path = "../alloy-rlp/crates/rlp" }
alloy-rlp-derive = { path = "../alloy-rlp/crates/rlp-derive" }
alloy-trie = { path = "../alloy-trie" }
alloy-chains = { path = "../alloy-chains" }
alloy-hardforks = { path = "../alloy-hardforks/crates/hardforks" }
alloy-eip2124 = { path = "../alloy-eips/crates/eip2124" }
alloy-eip2930 = { path = "../alloy-eips/crates/eip2930" }
alloy-eip7702 = { path = "../alloy-eips/crates/eip7702" }
alloy-eip7928 = { path = "../alloy-eips/crates/eip7928" }
alloy-eip8141 = { path = "../alloy-eips/crates/eip8141" }
revm = { path = "../revm/crates/revm" }
revm-bytecode = { path = "../revm/crates/bytecode" }
revm-context = { path = "../revm/crates/context" }
revm-context-interface = { path = "../revm/crates/context/interface" }
revm-database = { path = "../revm/crates/database" }
revm-database-interface = { path = "../revm/crates/database/interface" }
revm-handler = { path = "../revm/crates/handler" }
revm-inspector = { path = "../revm/crates/inspector" }
revm-interpreter = { path = "../revm/crates/interpreter" }
revm-precompile = { path = "../revm/crates/precompile" }
revm-primitives = { path = "../revm/crates/primitives" }
revm-state = { path = "../revm/crates/state" }
